on: pull_request
name: Pull Request Workflow
jobs:
  runTests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16, 18]
    steps:
      - uses: actions/checkout@v3
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v3.0.8
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: run build if cache
        if: steps.npm-cache.outputs.cache-hit == 'true'
        run: npm run build
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Execute tests
        run: npm run test
